config/routes.rb
Translatr::Application.routes.draw do

  resources :users , except: [:index]
  resources :sessions, only: [:create, :destroy, :new]
  resources :teams, shallow: true do 
    resources :texts do
      get 'personal', on: :collection
    end
    resources :translations
    resources :users, only: [:index] 
  end
  resources :user_teams
  resources :password_resets
  root 'sessions#new'
  match 'signout', to: 'sessions#destroy', via: :delete
  match 'request', to: 'user_teams#update', via: :put

  

end

app/models/user_team.rb
class UserTeam < ActiveRecord::Base
  after_create :send_invite_email

  belongs_to :user
  belongs_to :team

  state_machine :state, initial: :requested do

    state :accepted
    state :kicked 
    state :denied
    
    event :accept do
      transition any => :accepted
    end

    event :kick do
      transition any => :kicked
    end
    
    event :deny do
      transition any => :denied
    end
  end

  private

  def send_invite_email
    MemberMailer.group_invitation_notification(self).deliver
  end
end

app/controllers/user_teams_controller.rb
class UserTeamsController < ApplicationController

  def create
    @request = UserTeam.new(user_team_params)
    if @request.save
      redirect_to team_users_path(@request.team), success: 'Gruba katılım isteği gönerildi'
    else
      redirect_to team_users_path(@request.team), danger: 'Gruba davet başarısız oldu lütfen tekrar dene'
    end
  end

  def index
    @user_teams = UserTeam.new
    @requests = UserTeam.where(user_id: current_user.id, state: 'requested').paginate(
                                      page: params[:page], per_page: 8)
  end

  def edit
    @relationship = current_resource
    @team = @relationship.team
  end

  def update
    @request = current_resource
    if params[:commit] == 'Kabul Et'
      @request.accept
      redirect_to user_path(current_user), success: 'Gruba katılma isteğini kabul ettiniz.'
    elsif params[:commit] == 'Reddet'
      @request.deny
      redirect_to user_teams_path, danger: 'Gruba katılma isteğini reddettiniz.'
    end
  end

  def destroy
    @relationship = current_resource
    if @relationship.destroy
      redirect_to team_path(@relationship.team), success: "#{@relationship.user.name} Gruptan Atıldı"
    else
      redirect_to team_path(@relationship.team), danger: 'Bir Hata Oluştu Lütfen Tekrar Deneyin'
    end
  end

  private 

  def user_team_params
    params.require(:user_team).permit(:user_id, :team_id, :state)
  end

  def current_resource
    @current_resource ||= UserTeam.find(params[:id]) if params[:id]
  end
end

app/helpers/user_teams_helper.rb
module UserTeamsHelper
  def group_invite_request
    UserTeam.where(user_id: current_user.id, state: 'requested')
  end

  def group_invite_request_team_leader(request)
    User.find(request.team.leader_id)
  end

  def name_of_the_team_leader_who_invited(request)
    User.find(request.team.leader_id).name + User.find(request.team.leader_id).last_name
  end

  def request_size
    group_invite_request.size
  end

  def user_has_requests?
    if group_invite_request.size == 0 
      false
    else
      true
    end
  end

  def accepted_user_teams
    UserTeam.where(user_id: current_user.id, state: 'accepted')
  end

  def user_has_accepted_team?
    if accepted_user_teams.size == 0 
      false
    elsif current_user.leader || accepted_user_teams.size > 0
      true
    end
  end

end

app/views/user_teams/edit.html.erb
<div class = 'row'>
  <h1 class = 'middle' >Gruptan Çıkmak istediğine eminmisin?</h1>
</div>

<div class = 'row'>
  <div class = 'col col-md6 middle'>
    <%= link_to 'Hayır', team_texts_path(@team), class: 'btn btn-primary btn-lg'%>
    <%= link_to 'Gruptan Çık', user_team_path(@relationship), method: :delete, class: 'btn btn-primary btn-lg'%>
  </div>
</div>

app/views/user_teams/index.html.erb
<div class="col-md-12">
  <div class="widget stacked widget-table action-table middle">
    <div class="widget-header">
      <i class="icon-edit"></i>
      <h3>Davet İsteği</h3>
    </div> <!-- /widget-header -->

    <div class="widget-content middle">
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th class = 'middle' >Davet Eden</th>
            <th class = 'middle' >Grup İsmi</th>
            <th class="middle">İşlem</th>
          </tr>
        </thead>
        <% @requests.each do |request| %>
          <tbody>
            <tr>
              <td class="td-actions">
                <%= name_of_the_team_leader_who_invited(request).titleize %>
              </td>
              <td class="td-actions"><%= request.team.name%></td>
              <td class="td-actions">
                <%= form_tag  request_path, method: :put do |f| %>
                  <%= hidden_field_tag :id, request.id %>
                  <%= submit_tag 'Kabul Et', class: 'btn btn-primary' %>
                  <%= submit_tag 'Reddet', class: 'btn btn-primary' %>
                <%end%>
              </td>
            </tr>
          </tbody>
        <%end%>
      </table>
    </div> <!-- /widget-content -->
  </div> <!-- /widget -->
  <div class = 'middle' %>
    <%= will_paginate @requests, renderer: BootstrapPagination::Rails%>
  <div> 
</div>