config/routes.rb
Translatr::Application.routes.draw do

  resources :users , except: [:index]
  resources :sessions, only: [:create, :destroy, :new]
  resources :teams, shallow: true do 
    resources :texts do
      get 'personal', on: :collection
    end
    resources :translations
    resources :users, only: [:index] 
  end
  resources :user_teams
  resources :password_resets
  root 'sessions#new'
  match 'signout', to: 'sessions#destroy', via: :delete
  match 'request', to: 'user_teams#update', via: :put

  

end

app/views/shared/_general_nav.html.erb
<nav class="navbar navbar-inverse" role="navigation">

<div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <i class="icon-cog"></i>
    </button>
    <%= link_to 'Translatr', root_url, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">

        <% if user_has_accepted_team? %>
          <li class="dropdown">

            <a href="javscript:;" class="dropdown-toggle" data-toggle="dropdown">
              <i class="icon-group"></i>
              Üye Olduğum Gruplar
              <b class="caret"></b>
            </a>

            <ul class="dropdown-menu">
              <% current_user.teams.each do |team| %>
                <li><%= link_to team.name, team_texts_path(team)  %></li>
              <%end%>
            </ul>

          </li>
        <%end %>

        <li class="dropdown">

          <a href="javscript:;" class="dropdown-toggle" data-toggle="dropdown">
            <% if user_has_requests? %>
              <span class="badge badge-warning"><%= request_size %> </span>
            <% end %>
            <i class="icon-user"></i> 
            <%= current_user.email %>
            <b class="caret"></b>
          </a>

          <ul class="dropdown-menu">
            <% if user_has_requests? %> 
              <li><%= link_to user_teams_path do %>
                <li><span class="badge badge-warning"><%= request_size %></span> Katılım İsteği</li>
              <%end%></li>
            <%end%>
            <li><%= link_to 'Grup Oluştur', new_team_path %></li>
            <li><%= link_to 'Profil', edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to 'Çıkış Yap', signout_path, method: 'delete' %></li>
          </ul>

        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div> <!-- /.container -->
  </nav>

app/views/shared/_general_nav_no_login.html.erb
<nav class="navbar navbar-inverse" role="navigation">

<div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <i class="icon-cog"></i>
    </button>
    <%= link_to 'Translatr', root_url, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
          <%= link_to 'Kayıt', new_user_path %>
      </li> 
      <li class="dropdown"> 
          <%= link_to 'Giriş', new_session_path %>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</div> <!-- /.container -->
</nav>

app/views/shared/_group_info.html.erb
<% current_user.teams.each do |team| %>
  <div class="col-md-6">

    <div class="widget stacked widget-table action-table">

      <div class="widget-header">
        <i class="icon-group"></i>
        <h3>Grup- <%= team.name %></h3>
      </div> <!-- /widget-header -->

      <div class="widget-content middle">

        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th class = 'middle'>İsim</th>
              <th class = 'middle'>Mail Adresi</th>
              <th class="td-actions middle">Yazı Sayısı</th>
            </tr>
          </thead>
          <tbody>
            <% team.users.each do |user| %>
              <tr>
                <td><%= user.name.titleize%></td>
                <td><%= user.email %></td>
                <td><%= user.texts.size %> </td>
              </tr>
            <%end%>
          </tbody>
        </table>
      </div> <!-- /widget-content -->
    </div> <!-- /widget -->
  </div>
<%end%>

app/views/shared/_team_nav.html.erb
<% if current_page?(team_texts_path(@team)) %>
  <li class="active">
    <%= link_to team_texts_path(@team) do %>
      <span class="badge pull-right"><%= @team.texts.size %></span>
      Tüm Çeviriler
    <%end%>
  </li>
<%else%>
  <li>
    <%= link_to team_texts_path(@team) do %>
      <span class="badge pull-right"><%= @team.texts.size %></span>
      Tüm Çeviriler
    <%end%>
  </li>
<%end%>

<% if current_page?(personal_team_texts_path(@team)) %>
  <% if allow? :texts, :personal %>
    <li class = 'active'>
      <%= link_to personal_team_texts_path(@team) do %>
        <span class="badge pull-right"><%= @personal_texts.size %></span>
        Benim Çevirilerim
      <%end%>
    </li>
  <%end%>
<%else%>
  <% if allow? :texts, :personal %>
    <li>  
      <%= link_to personal_team_texts_path(@team) do %>
        <span class="badge pull-right"><%= @personal_texts.size %></span>
        Benim Çevirilerim
      <%end%>
    </li>
  <%end%>
<%end%>

<% if current_page?(team_translations_path(@team)) %>
  <% if allow? :translations, :index %>
    <li class = 'active'>
      <%= link_to team_translations_path(@team) do %>
        <span class="badge pull-right"><%= @untranslated.size %></span>
        Çevrilmemiş Metinler
      <%end%>
    </li>
  <%end%>
<%else%>
  <% if allow? :translations, :index %>
    <li>  
      <%= link_to team_translations_path(@team) do %>
        <span class="badge pull-right"><%= @untranslated.size %></span>
        Çevrilmemiş Metinler
      <%end%>
    </li>
  <%end%>
<%end%>

<% if current_page?(new_team_text_path(@team)) %>
  <% if allow? :texts, :new%>
    <li class = 'active' ><%= link_to 'Yeni Çeviri', new_team_text_path(@team) %> </li>
  <%end%>
<%else%>
  <% if allow? :texts, :new%>
    <li><%= link_to 'Yeni Çeviri', new_team_text_path(@team) %></li>
  <%end%>
<%end%>

<% if current_page?(team_path(@team)) %>
    <% if allow? :teams, :show, @team %>
      <li class = 'active'><%= link_to 'Grubu Yönet', team_path(@team) %></li>
    <%end%>
<% else %>
    <% if allow? :teams, :show, @team %>
      <li><%= link_to 'Grubu Yönet', team_path(@team) %></li>
    <%end%>
<%end%>

<% if current_page?(team_users_path(@team)) %>
    <% if allow? :users, :index %>
      <li class = 'active'><%= link_to 'Gruba Ekle', team_users_path(@team) %></li>
    <%end%>
<% else %>
    <% if allow? :users, :index %>
      <li><%= link_to 'Gruba Ekle', team_users_path(@team) %></li>
    <%end%>
<%end%>

<% if current_page?(edit_user_team_path(@relationship)) %>
    <% if allow? :user_teams, :edit, @relationship %>
      <li class = 'active' ><%= link_to 'Gruptan Çık', edit_user_team_path(@relationship) %></li>
    <%end%>
<% else %>
    <% if allow? :user_teams, :edit, @relationship %>
      <li><%= link_to 'Gruptan Çık', edit_user_team_path(@relationship) %></li>
    <%end%>
<%end%>

app/views/shared/_text_and_author_info.html.erb
<div class="col-md-6">
  <div class="widget stacked">
    <div class="widget-header middle">
      <i class="icon-file"></i>
      <h3> Metin </h3>
    </div> <!-- /widget-header -->
    <div class="widget-content middle">
      <%= @text.text %>

      <div class="panel panel-default down">
        <div class="panel-body">
          <div class="col-md-12">
            <div class="media">
              <a class="pull-left" href="#">
                <% if @text.user.avatar.exists? %>
                  <%= image_tag @text.user.avatar.url(:media) %>
                <%else%>
                  <%= image_tag 'media_placeholder.png' %>
                <%end%>
              </a>
              <div class="media-body pull-left">
                <h4 class="media-heading"><%= @text.user.name %></h4>
                <h5><small>
                    <%= t distance_of_time_in_words_to_now(@text.created_at) + ' önce'%>
                </small></h5>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div> <!-- /widget-content -->
  </div> <!-- /widget -->
</div> <!-- /span6 -->

app/views/shared/_text_display.html.erb
<% @texts.each do |text| %>
  <div class="col-md-6">
    <div class="widget stacked">
      <div class="widget-header middle">
        <i class="icon-file"></i>
        <h3>Çevrilecek</h3>
      </div> <!-- /widget-header -->
      <div class="widget-content middle">
        <%= link_to text.title, text_path(text), class: "news-item-title" %>     
        <p><%= excerpt(text.text, text.text.split.first, radius: 80) %></p>
      </div> <!-- /widget-content -->
    </div> <!-- /widget -->
  </div> <!-- /span6 -->
<%end%>

app/views/shared/_texts_info.html.erb
  <div class="col-md-6">

    <div class="widget stacked widget-table action-table">

      <div class="widget-header">
        <i class="icon-group"></i>
        <h3> Son Çevirttiklerim</h3>
      </div> <!-- /widget-header -->

      <div class="widget-content middle">

        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th class = 'middle'>Metin Başlığı</th>
              <th class = 'middle'>Çeviri Durumu</th>
            </tr>
          </thead>
          <tbody>
            <% @texts.each do |text| %>
              <tr>
                <td><%= link_to text.title, text_path(text) %></td>
                <td> 
                  <button type = 'button' class = 'btn btn-info'>
                    <%= check_for_translation(text) %>
                  </button>
                </td>
              </tr>
            <%end%>
          </tbody>
        </table>
      </div> <!-- /widget-content -->
    </div> <!-- /widget -->
  </div>

app/views/shared/_translation_and_author_info.html.erb
<div class="col-md-6">
  <div class="widget stacked">
    <div class="widget-header middle">
      <i class="icon-file"></i>
      <h3>Çeviri</h3>
    </div> <!-- /widget-header -->
    <div class="widget-content middle">
      <%= @text.translation.translation_text %>

      <div class="panel panel-default down">
        <div class="panel-body">
          <div class="col-md-12">
            <div class="media">
              <a class="pull-left" href="#">
                <% if @text.translation.user.avatar.exists? %>
                  <%= image_tag @text.translation.user.avatar.url(:media) %>
                <%else%>
                  <%= image_tag 'media_placeholder.png' %>
                <%end%>
              </a>
              <div class="media-body pull-left">
                <h4 class="media-heading"><%= @text.translation.user.name %></h4>
                <h5><small>
                    <%= t distance_of_time_in_words_to_now(@text.translation.created_at) + ' önce'%>
                </small></h5>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div> <!-- /widget-content -->
  </div> <!-- /widget -->
</div> <!-- /span6 -->

app/views/shared/_translations_info.html.erb
<div class="col-md-6">

  <div class="widget stacked widget-table action-table">

    <div class="widget-header">
      <i class="icon-group"></i>
      <h3> Çeviri Bekleyenler</h3>
    </div> <!-- /widget-header -->

    <div class="widget-content middle">

      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th class = 'middle'>Metin Başlığı</th>
            <th class = 'middle'>Çeviri Durumu</th>
          </tr>
        </thead>
        <tbody>
          <% texts_without_translation.each do |untranslated| %>
            <tr>
              <td><%= link_to untranslated.title, text_path(untranslated) %></td>
              <td> 
                <button type = 'button' class = 'btn btn-info'>
                  Çevrilmedi
                </button>
              </td>
            </tr>
          <%end%>
        </tbody>
      </table>
    </div> <!-- /widget-content -->
  </div> <!-- /widget -->
</div>