config/routes.rb
Translatr::Application.routes.draw do

  resources :users , except: [:index]
  resources :sessions, only: [:create, :destroy, :new]
  resources :teams, shallow: true do 
    resources :texts do
      get 'personal', on: :collection
    end
    resources :translations
    resources :users, only: [:index] 
  end
  resources :user_teams
  resources :password_resets
  root 'sessions#new'
  match 'signout', to: 'sessions#destroy', via: :delete
  match 'request', to: 'user_teams#update', via: :put

  

end

app/models/text.rb
class Text < ActiveRecord::Base
  scope :latest, -> { order(created_at: :desc).limit(5) } 

  after_create :send_notification_email
  after_update :send_update_notification
  
  belongs_to :user
  belongs_to :team
  has_one :translation, dependent: :destroy

  validates :title, presence: true
  validates :text, presence: true
  validates :user_id, presence: true

  private

  def send_notification_email
    MemberMailer.text_creation_notification(self).deliver
  end

  def send_update_notification
    MemberMailer.text_update_notification(self).deliver
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_filter :check_for_team, only: [:index, :personal]

  def new
    @text = Text.new
    variables_for_team_nav
  end

  def create
    @team = Team.find(params[:team_id])
    @text = @team.texts.new(text_params)
    @text.user_id = current_user.id
    if @text.save
      redirect_to new_team_text_path(params[:team_id]),  success: 'Çeviri başarılı şekilde kaydedildi.'
    else
      redirect_to new_team_text_path(params[:team_id]), danger: 'Çeviri oluşturulması sırasında bir hata oluştu lütfen tekrar deneyin.' 
    end
  end

  def index
    variables_for_team_nav
  end
  
  def show
    @text = current_resource
    @team = @text.team
    @translation = Translation.new
  end

  def edit
    @text = current_resource
  end

  def destroy
    @text = current_resource
    @team = @text.team
    if @text.destroy
      redirect_to team_texts_path(@team), success: 'Yazınız ve varsa çevirisi silindi'
    end
  end
  
  def update
    @text = current_resource
    if @text.update(text_params)
      redirect_to text_path(@text), success: 'Çeviri başarılı bir şekilde editlendi'
    end
  end

  def personal
    variables_for_team_nav
  end

  private

  def text_params
    params.require(:text).permit(:title, :text, :team_id)
  end

  def current_resource
    @current_resource ||= Text.find(params[:id]) if params[:id]
  end

  def check_for_team
    @team = Team.find(params[:team_id])
    if !@team.in?(current_user.teams)
      redirect_to root_url, danger: 'Bunu yapmaya izniniz yok'
    end
  end

  def variables_for_team_nav
    @team = Team.find(params[:team_id])
    @relationship = UserTeam.where(team_id: @team.id, user_id: current_user.id, state: 'accepted').take
    @personal_texts = @team.texts.where(user_id: current_user.id).paginate(page: params[:page], per_page: 6)
    @untranslated = @team.texts.where{id.not_in Translation.select{text_id}.uniq}.paginate(page: params[:page], per_page: 6)
    @texts = @team.texts.paginate(page: params[:page], per_page: 6)
  end
end

app/views/texts/edit.html.erb
<div class = "row" >
  <div class="col-md-6">
    <div class="widget stacked">
      <div class="widget-header middle">
        <i class="icon-file"></i>
        <h3><%= @text.title %></h3>
      </div> <!-- /widget-header -->
      <div class="widget-content middle">
        <%= @text.text %>
      </div> <!-- /widget-content -->
    </div> <!-- /widget -->
  </div> <!-- /span6 -->
  <div class="col-md-6">
    <div class="widget stacked">
      <div class="widget-header middle">
        <i class="icon-file"></i>
        <h3>Editle</h3>
      </div> <!-- /widget-header -->
      <div class="widget-content middle">
        <%= form_for :text, url: text_path(@text.id),  method: :patch do |f| %>
          <div class = "form-group">
            <%= f.text_area :text, :placeholder => 'Yeni yazıyı buraya girin', class: 'form-control', rows: 6 %>
          </div>
          <div class = "form-group">
            <%= f.submit 'Tamamdır', class: 'btn btn-primary' %>
          </div>
        <%end%>
      </div> <!-- /widget-content -->
    </div> <!-- /widget -->
  </div> <!-- /span6 -->
</div>

app/views/texts/new.html.erb
<div class="row">
  <div class="col-md-4">
    <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
      <%= render 'shared/team_nav' %>
    </ul>
  </div>
  <div class="col-md-8">
    <div class="widget stacked">
      <div class="widget-header">
        <i class="icon-tasks"></i>
        <h3>Yeni Çevrilecek Metin</h3>
      </div> <!-- /.widget-header -->
      <div class="widget-content">
        <%= form_for [@team, @text] do |f| %>
          <div class="form-group">
            <%= f.text_field :title, :placeholder => 'Başlık', class: "form-control" %>
          </div> <!-- /.form-group -->
          <div class="form-group">
            <%= f.text_area :text, :placeholder => 'Çevrilecekler', class: "form-control", rows: 8%>
          </div> <!-- /.form-group -->
          <div class="form-group">
            <%= f.submit 'Gönder', class: "btn btn-default" %>
          </div> <!-- /.form-group -->
        <%end%>
      </div> <!-- /.widget-content -->
    </div> <!-- /.widget -->
  </div> <!-- /.col-md-12 -->
</div> <!-- /.row -->

app/views/texts/personal.html.erb
<div class="main">
  <div class="row">
    <div class="col-md-4">
      <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
        <%= render 'shared/team_nav' %>
      </ul>
    </div>
    <div class="col-md-8">
      <div class="row">
        <% @personal_texts.each do |text| %>
          <div class="col-md-6">
            <div class="widget stacked">
              <div class="widget-header middle">
                <i class="icon-file"></i>
                <h3>Çevrilecek</h3>
              </div> <!-- /widget-header -->
              <div class="widget-content middle">
                <%= link_to text.title, text_path(text), class: "news-item-title" %>     
                <p><%= excerpt(text.text, text.text.split.first, radius: 80) %></p>
              </div> <!-- /widget-content -->
            </div> <!-- /widget -->
          </div> <!-- /span6 -->
        <%end%>
      </div>
      <div class = 'middle' >
        <%= will_paginate @texts, renderer: BootstrapPagination::Rails%>
      </div>
    </div>
  </div>
</div>

app/views/texts/show.html.erb
<div class = "row">
  <div class="col-md-12 middle push-down">
    <% if allow? :texts, :destroy, @text %>
      <%= link_to "Yazıyı Sil", text_path(@text), method: 'delete', class: 'btn btn-default' %>
    <%end%>
    <% if allow? :texts, :edit, @text %>
      <%= link_to "Yazıyı Editle", edit_text_path(@text), class: 'btn btn-default' %>
    <%end%>
    <% if allow? :translations, :destroy, @text.translation %>
      <%= link_to "Çeviriyi Sil", translation_path(@text.translation), method: 'delete', class: 'btn btn-default'%>
    <%end%>
    <% if allow? :translations, :edit, @text.translation %>
      <%= link_to "Çeviriyi Editle", edit_translation_path(@text.translation), class: 'btn btn-default'%>
    <%end%>
  </div>
</div>

<div class = "row" >
  <%= render 'shared/text_and_author_info' %>

  <% if @text.translation %>
    <%= render 'shared/translation_and_author_info' %>
  <%end%>

  <% if current_user.translator && !@text.translation %>
    <div class="col-md-6">
      <div class="widget stacked">
        <div class="widget-header middle">
          <i class="icon-file"></i>
          <h3>Çeviri</h3>
        </div> <!-- /widget-header -->
        <div class="widget-content middle">
          <%= form_for [@team, @translation] do |f| %>
            <div class = "form-group">
              <%= f.text_area :translation_text, :placeholder => 'Çeviri Metninini Buraya Giriniz', class: 'form-control', rows: 6 %>
            </div>
            <%= f.hidden_field :text_id, :value => params[:id] %>
            <div class = "form-group">
              <%= f.submit 'Çevir', class: 'btn btn-primary' %>
            </div>
          <%end%>

        </div> <!-- /widget-content -->
      </div> <!-- /widget -->
    </div> <!-- /span6 -->
  <%end%> 
</div>